version = "3.9.8"
runner.dialect = scala3
maxColumn = 120
lineEndings = unix
importSelectors = singleLine

align.preset = none

align {
    tokens = [ {code = "=>", owner = "Case|Type.Arg.ByName"}, "<-", "->", "%", "%%" ]
    arrowEnumeratorGenerator = true
    openParenCallSite = false
    openParenDefnSite = false
}

binPack {
    parentConstructors = true
}

continuationIndent {
    callSite = 2
    defnSite = 2
}

docstrings {
    # `wrap` is a buggy "feature" that even they admit will not format all scaladocs correctly.
    # Could try to enable it again in v3.8.2 to see if it's any better.
    wrap = no
}

newlines {
    penalizeSingleSelectMultiArgList = false
    avoidInResultType = true
}

rewrite {
    rules = [RedundantBraces, RedundantParens, Imports]
    imports.sort = ascii

    redundantBraces {
        maxLines = 120
        includeUnitMethods = true
        stringInterpolation = true
    }
}

spaces {
    inImportCurlyBraces = true
    beforeContextBoundColon = false
}

assumeStandardLibraryStripMargin = true